'use strict';
// Regenerates src/renderer/icons.js from the lucide-static package (dev dependency).
// Usage: node scripts/gen-icons.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dir = path.join(root, 'node_modules/lucide-static/icons/');
const current = require(path.join(root, 'src/renderer/icons.js')).ICONS;
const names = [...new Set([...Object.keys(current), ...process.argv.slice(2)])];
const out = {};
for (const n of names) {
  const s = fs.readFileSync(dir + n + '.svg', 'utf8');
  out[n] = s.replace(/<!--.*?-->/s, '').match(/>([\s\S]*)<\/svg>/)[1].replace(/\s+/g, ' ').trim();
}
const fn = 'function icon(name, size = 16) {\n' +
  '  return `<svg class="ic" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name] || ""}</svg>`;\n}\n';
fs.writeFileSync(path.join(root, 'src/renderer/icons.js'),
  '// Icon paths from lucide-static (ISC licence), generated by scripts/gen-icons.js.\n' +
  '// Add icons with: node scripts/gen-icons.js <name> ...\n' +
  'const ICONS = ' + JSON.stringify(out, null, 1) + ';\n' + fn +
  'if (typeof module !== "undefined") module.exports = { ICONS, icon };\n');
console.log(`${names.length} icons`);
